safe: true
lsi: false
highlighter: rouge
baseurl: /rbbt
markdown: kramdown
singularity_image_url: https://b2drop.bsc.es/index.php/s/D5rgH3paTefSw2K/download
singularity_HTS_image_url: https://b2drop.bsc.es/index.php/s/D5rgH3paTefSw2K/download
