require 'rbbt/util/rake'
require 'rbbt/sources/polysearch'
require 'rbbt/sources/pubmed'
require 'rbbt/sources/organism'

include Rake::Pipeline

desc "Translate gene ids to Entrez"
step :entrez do
  genes  = STDIN.read.split("\n").collect{|l| l.chomp.strip }
 
  index  = Organism.id_index('human')  
  entrez = index.values_at(*genes).compact.flatten.uniq

  entrez.join("\n")
end

desc "Load Pubmed IDs for genes in the list"
step :pmids do |t|
  entrez = input.split("\n")

  pmids = Organism.gene_literature('human').values_at(*entrez).compact.flatten.uniq
  
  pmids.join("\n")
end

desc "Download article abstracts and merge them into a meta-document"
step :metadoc do |t|
  pmids = input.split("\n")

  articles = PubMed.get_article(pmids)

  metadoc = articles.collect{|pmid, article|
    article.text
  }.join("\n")
  
  metadoc
end

desc "Find disease names in meta-document"
step :diseases do |t|
  metadoc = input

  disease_count = {}
  Polysearch.match(metadoc, ['disease']).values.flatten.each{|disease|
    disease_count[disease] ||= 0
    disease_count[disease] += 1
  }

  disease_count.collect{|disease, count| 
    "#{ disease }\t#{count}"
  }.join("\n")
end
